name: Deploy

on:
  push:
    branches:
      - main
    
jobs:  
  deploy:
    name: Deploy to PyXLabs-IpfsWorker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Deployment to PyXMaid Runner
        shell: bash
        env: 
          HOST: ${{ secrets.SERVER_HOST_PYXMAID }}
          PORT: ${{ secrets.SERVER_PORT_PYXMAID }}
          USERNAME: ${{ secrets.SERVER_USERNAME_PYXMAID }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY_PYXMAID }}
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.SSH_PRIVATE_KEY_PYXMAID }}")
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SERVER_PORT_PYXMAID }} -H ${{ secrets.SERVER_HOST_PYXMAID }} >> ~/.ssh/known_hosts
          workingpath=$(echo $RANDOM | md5sum | head -c 10; echo;)
          cd publish/
          tar czf - * | ssh -p ${{ secrets.SERVER_PORT_PYXMAID }} ${{ secrets.SERVER_USERNAME_PYXMAID }}@${{ secrets.SERVER_HOST_PYXMAID }} "mkdir -p ~/deployment$workingpath && cd ~/deployment$workingpath && tar xzf -"
          ssh -p ${{ secrets.SERVER_PORT_PYXMAID }} ${{ secrets.SERVER_USERNAME_PYXMAID }}@${{ secrets.SERVER_HOST_PYXMAID }} "cd ~/scripts && ./deployment.sh -p ~/deployment$workingpath"
